/**
 * Chatbot Controller - Handles chatbot API requests
 * 
 * This controller processes incoming chat messages and returns
 * appropriate responses from the chatbot service.
 * 
 * HEALTHCARE RESPONSIBILITY:
 * All responses are generated by the chatbotService which is
 * designed to provide safe, helpful guidance without medical advice.
 */

const chatbotService = require('../services/chatbotService');

/**
 * Handles incoming chat messages
 * 
 * @param {Object} req - Express request with message in body
 * @param {Object} res - Express response
 * @returns {Object} JSON response with bot reply
 */
const handleChatMessage = async (req, res) => {
  try {
    const { message } = req.body;

    // Validate message presence
    if (!message) {
      return res.status(400).json({
        success: false,
        error: 'Message is required'
      });
    }

    // Validate message type
    if (typeof message !== 'string') {
      return res.status(400).json({
        success: false,
        error: 'Message must be a string'
      });
    }

    // Validate message length (prevent abuse)
    if (message.length > 1000) {
      return res.status(400).json({
        success: false,
        error: 'Message is too long. Please keep it under 1000 characters.'
      });
    }

    // Process message through chatbot service
    const response = await chatbotService.processMessage(message);

    // Return successful response
    return res.status(200).json({
      success: true,
      reply: response.reply
    });

  } catch (error) {
    console.error('Chatbot error:', error.message);
    
    // Return safe error response
    return res.status(500).json({
      success: false,
      error: 'Unable to process your message. Please try again.',
      reply: 'I apologize, but I encountered an issue. Please try again or submit a support request through our form for personalized assistance.'
    });
  }
};

module.exports = {
  handleChatMessage
};
